<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.Master" AutoEventWireup="true" CodeBehind="Adminpage.aspx.cs" Inherits="FlightOnlineWeb.Adminpage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <div>
            <asp:GridView ID="idFlightView1" runat="server" AutoGenerateColumns="False" 
                DataKeyNames="flightId" AutoGenerateDeleteButton="True"
                AutoGenerateEditButton="True" onrowcancelingedit="idFlightView_RowCancelingEdit"   
                onrowdeleting="idFlightView_RowDeleting" onrowediting="idFlightView_RowEditing"   
                onrowupdating="idFlightView_RowUpdating" ">
                <Columns>
                    <asp:TemplateField HeaderText="HeaderFlightId" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtFlightNameId" runat="server" Text='<%# Bind("flightId") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelFlightNameId" runat="server" Text='<%# Bind("flightId") %>'></asp:Label>  
                            </itemtemplate>
            </asp:TemplateField>
                     <asp:TemplateField HeaderText="FLIGHT NAME" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtFlightName" runat="server" Text='<%# Bind("flightName") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelFlightName" runat="server" Text='<%# Bind("flightName") %>'></asp:Label>  
                            </itemtemplate>
            </asp:TemplateField>
                    <asp:TemplateField HeaderText="FLIGHT NUMBER" runat="server">
                <edititemtemplate>  
                                <asp:TextBox ID="TxtFlightNumber" runat="server" Text='<%# Bind("flightNumber") %>'></asp:TextBox> 
                                </edititemtemplate>
                <itemtemplate>  
                                <asp:Label ID="LabelFlightNumber" runat="server" Text='<%# Bind("flightNumber") %>'></asp:Label>  
                            </itemtemplate>
                        </asp:TemplateField>
                </Columns>
            </asp:GridView>
        </div>
</asp:Content>
